version: '3'
services:

  api:
    build: .
    hostname: weather_api
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 4000:4000

  db:
    image: postgres
    hostname: weather_db
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - weather_data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  weather_data:
